---
version: "2"

services:
  rancher-purge:
    image: troyharvey/rancher-purge
    scale: 2
    environment:
      - RANCHER_ENVIRONMENT=${RANCHER_ENVIRONMENT}
      - RANCHER_URL=${RANCHER_URL}
      - RANCHER_ACCESS_KEY=${RANCHER_ACCESS_KEY}
      - RANCHER_SECRET_KEY=${RANCHER_SECRET_KEY}
      - RANCHER_CLIENT_DEBUG=${RANCHER_CLIENT_DEBUG}
      - INTERVAL=180
    labels:
      # Anti-affinity to run the two containers on different hosts.
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
